<?php
/**
 * ResultsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Qase\APIClientV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Qase.io TestOps API v2
 *
 * Qase TestOps API v2 Specification.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@qase.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Qase\APIClientV2\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Qase\APIClientV2\ApiException;
use Qase\APIClientV2\Configuration;
use Qase\APIClientV2\HeaderSelector;
use Qase\APIClientV2\ObjectSerializer;

/**
 * ResultsApi Class Doc Comment
 *
 * @category Class
 * @package  Qase\APIClientV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ResultsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createResultV2' => [
            'application/json',
        ],
        'createResultsV2' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createResultV2
     *
     * Create test run result
     *
     * @param  string $projectCode projectCode (required)
     * @param  int $runId runId (required)
     * @param  \Qase\APIClientV2\Model\ResultCreate $resultCreate resultCreate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createResultV2'] to see the possible values for this operation
     *
     * @throws \Qase\APIClientV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function createResultV2($projectCode, $runId, $resultCreate, string $contentType = self::contentTypes['createResultV2'][0])
    {
        $this->createResultV2WithHttpInfo($projectCode, $runId, $resultCreate, $contentType);
    }

    /**
     * Operation createResultV2WithHttpInfo
     *
     * Create test run result
     *
     * @param  string $projectCode (required)
     * @param  int $runId (required)
     * @param  \Qase\APIClientV2\Model\ResultCreate $resultCreate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createResultV2'] to see the possible values for this operation
     *
     * @throws \Qase\APIClientV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function createResultV2WithHttpInfo($projectCode, $runId, $resultCreate, string $contentType = self::contentTypes['createResultV2'][0])
    {
        $request = $this->createResultV2Request($projectCode, $runId, $resultCreate, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Qase\APIClientV2\Model\CreateResultV2422Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createResultV2Async
     *
     * Create test run result
     *
     * @param  string $projectCode (required)
     * @param  int $runId (required)
     * @param  \Qase\APIClientV2\Model\ResultCreate $resultCreate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createResultV2'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createResultV2Async($projectCode, $runId, $resultCreate, string $contentType = self::contentTypes['createResultV2'][0])
    {
        return $this->createResultV2AsyncWithHttpInfo($projectCode, $runId, $resultCreate, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createResultV2AsyncWithHttpInfo
     *
     * Create test run result
     *
     * @param  string $projectCode (required)
     * @param  int $runId (required)
     * @param  \Qase\APIClientV2\Model\ResultCreate $resultCreate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createResultV2'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createResultV2AsyncWithHttpInfo($projectCode, $runId, $resultCreate, string $contentType = self::contentTypes['createResultV2'][0])
    {
        $returnType = '';
        $request = $this->createResultV2Request($projectCode, $runId, $resultCreate, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createResultV2'
     *
     * @param  string $projectCode (required)
     * @param  int $runId (required)
     * @param  \Qase\APIClientV2\Model\ResultCreate $resultCreate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createResultV2'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createResultV2Request($projectCode, $runId, $resultCreate, string $contentType = self::contentTypes['createResultV2'][0])
    {

        // verify the required parameter 'projectCode' is set
        if ($projectCode === null || (is_array($projectCode) && count($projectCode) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $projectCode when calling createResultV2'
            );
        }

        // verify the required parameter 'runId' is set
        if ($runId === null || (is_array($runId) && count($runId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $runId when calling createResultV2'
            );
        }

        // verify the required parameter 'resultCreate' is set
        if ($resultCreate === null || (is_array($resultCreate) && count($resultCreate) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $resultCreate when calling createResultV2'
            );
        }


        $resourcePath = '/{project_code}/run/{run_id}/result';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($projectCode !== null) {
            $resourcePath = str_replace(
                '{' . 'project_code' . '}',
                ObjectSerializer::toPathValue($projectCode),
                $resourcePath
            );
        }
        // path params
        if ($runId !== null) {
            $resourcePath = str_replace(
                '{' . 'run_id' . '}',
                ObjectSerializer::toPathValue($runId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($resultCreate)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($resultCreate));
            } else {
                $httpBody = $resultCreate;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation createResultsV2
     *
     * Bulk create test run result
     *
     * @param  string $projectCode projectCode (required)
     * @param  int $runId runId (required)
     * @param  \Qase\APIClientV2\Model\CreateResultsRequestV2 $createResultsRequestV2 createResultsRequestV2 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createResultsV2'] to see the possible values for this operation
     *
     * @throws \Qase\APIClientV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function createResultsV2($projectCode, $runId, $createResultsRequestV2, string $contentType = self::contentTypes['createResultsV2'][0])
    {
        $this->createResultsV2WithHttpInfo($projectCode, $runId, $createResultsRequestV2, $contentType);
    }

    /**
     * Operation createResultsV2WithHttpInfo
     *
     * Bulk create test run result
     *
     * @param  string $projectCode (required)
     * @param  int $runId (required)
     * @param  \Qase\APIClientV2\Model\CreateResultsRequestV2 $createResultsRequestV2 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createResultsV2'] to see the possible values for this operation
     *
     * @throws \Qase\APIClientV2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function createResultsV2WithHttpInfo($projectCode, $runId, $createResultsRequestV2, string $contentType = self::contentTypes['createResultsV2'][0])
    {
        $request = $this->createResultsV2Request($projectCode, $runId, $createResultsRequestV2, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Qase\APIClientV2\Model\CreateResultV2422Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createResultsV2Async
     *
     * Bulk create test run result
     *
     * @param  string $projectCode (required)
     * @param  int $runId (required)
     * @param  \Qase\APIClientV2\Model\CreateResultsRequestV2 $createResultsRequestV2 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createResultsV2'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createResultsV2Async($projectCode, $runId, $createResultsRequestV2, string $contentType = self::contentTypes['createResultsV2'][0])
    {
        return $this->createResultsV2AsyncWithHttpInfo($projectCode, $runId, $createResultsRequestV2, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createResultsV2AsyncWithHttpInfo
     *
     * Bulk create test run result
     *
     * @param  string $projectCode (required)
     * @param  int $runId (required)
     * @param  \Qase\APIClientV2\Model\CreateResultsRequestV2 $createResultsRequestV2 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createResultsV2'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createResultsV2AsyncWithHttpInfo($projectCode, $runId, $createResultsRequestV2, string $contentType = self::contentTypes['createResultsV2'][0])
    {
        $returnType = '';
        $request = $this->createResultsV2Request($projectCode, $runId, $createResultsRequestV2, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createResultsV2'
     *
     * @param  string $projectCode (required)
     * @param  int $runId (required)
     * @param  \Qase\APIClientV2\Model\CreateResultsRequestV2 $createResultsRequestV2 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createResultsV2'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createResultsV2Request($projectCode, $runId, $createResultsRequestV2, string $contentType = self::contentTypes['createResultsV2'][0])
    {

        // verify the required parameter 'projectCode' is set
        if ($projectCode === null || (is_array($projectCode) && count($projectCode) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $projectCode when calling createResultsV2'
            );
        }

        // verify the required parameter 'runId' is set
        if ($runId === null || (is_array($runId) && count($runId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $runId when calling createResultsV2'
            );
        }

        // verify the required parameter 'createResultsRequestV2' is set
        if ($createResultsRequestV2 === null || (is_array($createResultsRequestV2) && count($createResultsRequestV2) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $createResultsRequestV2 when calling createResultsV2'
            );
        }


        $resourcePath = '/{project_code}/run/{run_id}/results';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($projectCode !== null) {
            $resourcePath = str_replace(
                '{' . 'project_code' . '}',
                ObjectSerializer::toPathValue($projectCode),
                $resourcePath
            );
        }
        // path params
        if ($runId !== null) {
            $resourcePath = str_replace(
                '{' . 'run_id' . '}',
                ObjectSerializer::toPathValue($runId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($createResultsRequestV2)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($createResultsRequestV2));
            } else {
                $httpBody = $createResultsRequestV2;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
