<?php
/**
 * BaseErrorFieldResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Qase\APIClientV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Qase.io TestOps API v2
 *
 * Qase TestOps API v2 Specification.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@qase.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Qase\APIClientV2\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * BaseErrorFieldResponseTest Class Doc Comment
 *
 * @category    Class
 * @description BaseErrorFieldResponse
 * @package     Qase\APIClientV2
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BaseErrorFieldResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BaseErrorFieldResponse"
     */
    public function testBaseErrorFieldResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "errorFields"
     */
    public function testPropertyErrorFields()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
