<?php
/**
 * ResultsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Qase\APIClientV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Qase.io TestOps API v2
 *
 * Qase TestOps API v2 Specification.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@qase.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Qase\APIClientV2\Test\Api;

use \Qase\APIClientV2\Configuration;
use \Qase\APIClientV2\ApiException;
use \Qase\APIClientV2\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ResultsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Qase\APIClientV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ResultsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createResultV2
     *
     * Create test run result.
     *
     */
    public function testCreateResultV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createResultsV2
     *
     * Bulk create test run result.
     *
     */
    public function testCreateResultsV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
